POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNhdCBIYXZlciIsImlkIjoiNjQxNTQ3YTZiOWJhZDZkNGI2NGU5MWFmIiwiaWF0IjoxNjc5MTk3NDMwfQ.uGvagVXm6P2QXO2ofVK30QrIxJL2tJgDhqunSlrBAz8

{
    "title": "Another Test, Another Test",
    "author": "Peanut", 
    "url": "catbeans.com",
    "likes": 20
}